apiVersion: v1
kind: Service
metadata:
  name: licarobeans
  labels:
    app: licarobeans
spec:
  selector:
    app: licarobeans
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: NodePort
